### ISSUE TITLE
Failed to Deploy Stack

### ISSUE THREAD

**Issue by FuckingToasters** [bagisto/bagisto-docker#18]
I always get following issue when trying to deploy the stack:
```
failed to deploy a stack: bagisto-php-apache Pulling bagisto-php-apache Warning failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount2113150479/Dockerfile: no such file or directory 
```

Now i tried to manually create it but then noticed that the number behind the file is always different and i'm not able to know what the next number is in order to create it. Here the different logs:
![image](https://github.com/bagisto/bagisto-docker/assets/94435104/a5faa3f9-5fab-43db-b6a9-6b7cabd6c932)

Here the compose file i use:
```yml
version: '3'

services:
    bagisto-php-apache:
        build:
            args:
                container_project_path: /var/www/html/
                uid: 1000
                user: Infinimonster
        image: bagisto-php-apache
        volumes:
            - ./workspace/:/var/www/html/
        networks:
            - webproxy
        restart: always

    bagisto-mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_HOST: "localhost"
            MYSQL_ROOT_PASSWORD: "0ytvUJJ29eQSJ5c9MRopeZreD5DWEJuMyrHIThPMyZ9vw7ILud"
        volumes:
            - ./.configs/mysql-data:/var/lib/mysql/
        networks:
            - webproxy
        restart: always

    bagisto-redis:
        image: redis:6.2-alpine
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - ./.configs/redis-data:/data
        networks:
            - webproxy
        restart: always

    bagisto-phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: bagisto-mysql
            PMA_USER: root
            PMA_PASSWORD: egehDBZ7aXVhoub5AIc13OsgwEolxrLDrg9klxZATa9OmKTLHf
            UPLOAD_LIMIT: 512M
        networks:
            - webproxy
        restart: always

    bagisto-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - ./.configs/elasticsearch-data:/var/lib/elasticsearch/data
        networks:
            - webproxy
        restart: always

    bagisto-kibana:
        image: docker.elastic.co/kibana/kibana:7.17.0
        environment:
            - ELASTICSEARCH_HOSTS=http://bagisto-elasticsearch:9200
        depends_on:
            - bagisto-elasticsearch
        networks:
            - webproxy
        restart: always

    bagisto-mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'
        networks:
            - webproxy
        restart: always

networks:
    webproxy:
        external: true
```
